DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 1e-4
  MAX_EPOCH: 200
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  #WEIGHT_DECAY: 0.01

TRAIN:
  PRINT_FREQ: 50

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  DPMoE:
    # ENABLE: True
    # ENABLE_CORRECTION: True
    FINETUNE_VIT_LN: False
    ENABLE_CORRECTION: True
    # FINETUNE_VIT_LN: False
    N_CTX: 8
#    # CTX_INIT: ['A photo of a', "An image of a", 'A drawing of a', 'A painting of a']
#    # CTX_INIT: ["A photo of a", "An image of a",  "A painting of a", "A photo of a big", "A photo of a small", "A photo of many"]
    CTX_INIT: False
    SH_WEIGHT: 0.5
    PREC: "amp"
    DA_WEIGHT: 1.0
